pliot:
  keycloak:
    url: "https://pinocloud.duckdns.org:8081"
    realmName: "master"
    realmManaged: "nemo"
    webClientId: "PinoDemo1_web_edge"
    user: "admin"
    password: "admin"
    clientId: "admin-cli"
  server:
    url: "https://pino-server-app-v17-prod.workload.nemo.onelab.eu"
  edge:
    name: "edge_name"
    tokenuri: ${pliot.keycloak.url}/realms/${pliot.keycloak.realmManaged}/protocol/openid-connect/token
    client-id: PinoDemo1_system_api
    client-secret: MjySu9sisABK2yHLA2fIQSbAxDzK2wWr
    edge-url: https://polyslot-1.pinomonitoring.click:8081
  base_path: "api"
  load_data: "false"
logging:
  file:
    path: ./log

springdoc:
  swagger-ui:
    path: "api-docs.html"

#jms:
 #  jndi-name: "java:/MyConnectionFactory"



spring:
  activemq:
    broker-url: "tcp://localhost:9876"
    user: "admin"
    password: "secret"
    pool:
      enabled: true
      max-connections: 10
  artemis:
    mode: native
    host: localhost
    port: 9876
    user: admin
    password: secret

#
#   jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
#          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
# https://hawt.io/docs/get-started.html
#

  jmx:
    enabled: true

  datasource:
    url: jdbc:postgresql://postgres:5432/pliot
    username: pliot
    password: pliot
#H2
#    url: jdbc:h2:file:./equipment
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
  jpa:
#    dialect: org.hibernate.dialect.H2Dialect
    dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql=true:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true


#
# Postgres
#
#spring:
# datasource:
#    url: jdbc:postgresql://localhost:25432/test
#    username: postgres
#    password: postgres
#  jpa:
#     hibernate: create
#      # <create | create-drop | update | validate | none>

#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${pliot.keycloak.url}/realms/${pliot.keycloak.realmManaged}/protocol/openid-connect/certs
          issuer-uri: ${pliot.keycloak.url}/realms/${pliot.keycloak.realmManaged}

server:
  port: 8081
  ssl:
    certificate: /app/config/letsencrypt/cert.pem
    certificate-private-key: /app/config/letsencrypt/key.pem
    #trust-certificate: /app/config/ca.pem

management:
  endpoints:
    web:
      exposure:
        include: hawtio,jolokia
      base-path: "/actuator"
      path-mapping:
        hawtio: "hawtio/console"
  management:
    security:
      enabled: false

hawtio:
  authenticationEnabled: false
