apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pino-mongodb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pino-mongodb.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
