apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nameOverride }}
  labels:
    app.kubernetes.io/name: {{ include "pino-mongodb.name" . }}
    nemo.eu/ingress-expose: "true"
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/name: {{ include "pino-mongodb.name" . }}
