springdoc:
  swagger-ui:
    path: "api-docs.html"

#jms:
 #  jndi-name: "java:/MyConnectionFactory"
spring:
  activemq:
    broker-url: "tcp://localhost:9876"
    user: "admin"
    password: "secret"
    pool:
      enabled: true
      max-connections: 10
  artemis:
    mode: native
    host: localhost
    port: 9876
    user: admin
    password: secret


#
# https://hawt.io/docs/get-started.html
#

  jmx:
    enabled: true

  datasource:
    url: jdbc:h2:file:./equipment
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql=true:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true

#
# Postgres
#
#spring:
# datasource:
#    url: jdbc:postgresql://localhost:25432/test
#    username: postgres
#    password: postgres
#  jpa:
#     hibernate: create
#      # <create | create-drop | update | validate | none>

#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: hawtio,jolokia
      base-path: "/actuator"
      path-mapping:
        hawtio: "hawtio/console"
  management:
    security:
      enabled: false

hawtio:
  authenticationEnabled: false
