architecture: standalone
auth:
  enabled: true
  rootPassword: G1us3pp3
  rootUser: root
commonLabels:
  nemo.eu/ingress-expose: 'true'
livenessProbe:
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 10
persistence:
  accessModes:
  - ReadWriteOnce
  enabled: true
  size: 8Gi
readinessProbe:
  failureThreshold: 6
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
resources:
  limits:
    cpu: 750m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 512Mi
service:
  nameOverride: pino-mongodb
