services:
  nemo_pino_edge:
    image: cogitoprediction/nemo_pino
    container_name: nemo_pino_edge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - /home/salvatore/pliot/docker/config:/app/config
      - /home/salvatore/pliot/docker/logs:/app/logs
    environment:
      JAVA_OPTS: ""
      SPRING_OPTS: ""
    extra_hosts:
      - "pinocloud.duckdns.org:13.53.207.26"

  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: pliot
      POSTGRES_USER: pliot
      POSTGRES_PASSWORD: pliot
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

volumes:
  pgdata:
