auth:
  database: postgres
  password: G1us3pp3
  postgresPassword: G1us3pp3
  secretKeys:
    userPasswordKey: ''
  username: pino
global:
  postgresql:
    auth:
      database: postgres
      password: G1us3pp3
      postgresPassword: G1us3pp3
      secretKeys:
        userPasswordKey: ''
      username: pino
    fullnameOverride: ''
    service:
      ports:
        postgresql: 5432
    postgresqlExtendedConf:
      listenAddresses: '*'
    pgHbaConfiguration: |
      host all all 0.0.0.0/0 md5
ingress:
  enabled: true
  className: ''
  annotations:
    nemo.eu/ingress-expose: "true"
    external-dns.alpha.kubernetes.io/hostname: pino-db-idp-v1.workload.nemo.onelab.eu
  hosts:
    - host: pino-db-idp-v1.workload.nemo.onelab.eu
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
ldap:
  enabled: false
 
primary:
  name: ''
 
service:
  port: 5432
  type: ClusterIP
 
serviceBindings:
  enabled: false
 
serviceAccount:
  create: true
  name: ''